#!/bin/bash
# 1_seed
# client-side script to be executed by remote ssh
# to do post-processing
#
# 1. create torrent
# 2. seed torrent
# 3. (fixme) transcode to smaller format
#
# parameters
#   $1 = RECORDING FILENAME

TARGET_DIR=/mnt/tv/recordings
TORRENT_DIR=/mnt/tv/torrents
TMP_DIR=/mnt/tv/tmp
WEB_DIR=/mnt/tv/webtorrents
LOG_FILE=/mnt/tv/log/myth.log

FILE=${1}

echo -n "[`date "+%Y-%m-%Oe %H:%M:%S"`]: " >> $LOG_FILE
echo ${FILE} >> $LOG_FILE
buildtorrent -a http://tv.olin.edu:6969/announce -l 2097152 "${TARGET_DIR}/${FILE}" "${TMP_DIR}/${FILE}.torrent"
/usr/local/bin/rtorrent_fast_resume.pl ${TARGET_DIR} < "${TMP_DIR}/${FILE}.torrent" > "${TORRENT_DIR}/${FILE}.torrent"
rm "${TMP_DIR}/${FILE}.torrent"
