#!/bin/bash
# do_transcode
# links the files that have yet to be transcoded
#
# parameters passed in
#   DIR
###

LOG_FILE=/home/mythtv/log/myth.log
RTORRENT_DIR=/home/mythtv/rtorrent
WEB_TORRENT_DIR=/home/mythtv/torrents
TMP_DIR=/home/mythtv/tmp

DIR=${1}

cd $DIR
for FILE in *
do
  echo "Considering on ${FILE}"
  if [ ! -f "${WEB_TORRENT_DIR}/${FILE}.torrent" ]
  then
    echo "Processing ${FILE}"
    buildtorrent -a http://mythtv.olin.edu:6969/announce -l 2097152 "${DIR}/${FILE}" "${WEB_TORRENT_DIR}/${FILE}.torrent"
    /usr/local/bin/rtorrent_fast_resume.pl ${DIR} < "${WEB_TORRENT_DIR}/${FILE}.torrent" > "${RTORRENT_DIR}/${FILE}.torrent"
  fi
  
done

