#!/bin/bash
# make_torrents
# make torrent files from a directory of videos
#
# parameters passed in
#   DIR
###

#RTORRENT_DIR=/mnt/tv/rtorrent
#WEB_TORRENT_DIR=/mnt/tv/torrents

DIR=${1}

echo "Looking in $DIR and outputting to $RTORRENT_DIR and $WEB_TORRENT_DIR"

cd $DIR
for FILE in *
do
  if [ ! -f "${WEB_TORRENT_DIR}/${FILE}.torrent" -o ! -s "${WEB_TORRENT_DIR}/${FILE}.torrent" ]
  then
    echo "Processing ${FILE}"
    buildtorrent -a http://mythtv.olin.edu:6969/announce -l 2097152 "${DIR}/${FILE}" "${WEB_TORRENT_DIR}/${FILE}.torrent"
    /usr/local/bin/rtorrent_fast_resume.pl ${DIR} < "${WEB_TORRENT_DIR}/${FILE}.torrent" > "${RTORRENT_DIR}/${FILE}.torrent"
  fi

  if [ ! -f "${RTORRENT_DIR}/${FILE}.torrent" ]
  then
    echo "Building rtorrent for ${FILE}"
    /usr/local/bin/rtorrent_fast_resume.pl ${DIR} < "${WEB_TORRENT_DIR}/${FILE}.torrent" > "${RTORRENT_DIR}/${FILE}.torrent"
  fi
  
done

