#!/bin/bash
# make_torrents
# make torrent files from a directory of videos
#
# parameters passed in
#   DIR
###

LOG_FILE=/mnt/tv/log/myth.log
RTORRENT_DIR=/mnt/tv/rtorrent
WEB_TORRENT_DIR=/mnt/tv/torrents
TMP_DIR=/mnt/tv/tmp

DIR=${1}

cd $DIR
for FILE in *
do
  echo "Considering on ${FILE}"
  if [ ! -f "${WEB_TORRENT_DIR}/${FILE}.torrent" ]
  then
    echo "Processing ${FILE}"
    buildtorrent -a http://mythtv.olin.edu:6969/announce -l 2097152 "${DIR}/${FILE}" "${WEB_TORRENT_DIR}/${FILE}.torrent"
    /usr/local/bin/rtorrent_fast_resume.pl ${DIR} < "${WEB_TORRENT_DIR}/${FILE}.torrent" > "${RTORRENT_DIR}/${FILE}.torrent"
  fi
  
done

