#!/bin/bash
# torrent_transcode
# prettifies names, creates torrents and seeds in rtorrent
# then pushes over ssh to the transcode slave to start transcoding
#
# parameters passed in
#   %DIR% %FILE% %TITLE% %SUBTITLE% %STARTTIMEISO%
###

LOG_FILE=/home/mythtv/log/myth.log
TARGET_DIR=/home/mythtv/recordings
SHARED_DIR=/var/lib/mythtv/recordings_pretty
TORRENT_DIR=/home/mythtv/torrents
TMP_DIR=/home/mythtv/tmp

DIR=${1}
FILE=${2}
TITLE=${3}
SUBTITLE=${4}
STARTTIMEISO=${5}

# --- fix subtitle
if [ -z "${SUBTITLE}" ]
then
  SUBTITLE="Untitled"
fi

# --- create filename
FIXEDISO=`echo "${STARTTIMEISO}" | sed -e 's/T/ /'`
DATE_STRING=`date --date "${FIXEDISO}" "+%Y-%m-%d, %I-%M %p"`
PRETTY_NAME="${TITLE} - ${DATE_STRING} - ${SUBTITLE}.${FILE##*.}"

# --- link to destination directory
echo -n "[`date "+%Y-%m-%Oe %H:%M:%S"`]: linking " >> $LOG_FILE
echo ${FILE} to ${PRETTY_NAME} >> $LOG_FILE
ln -s "${DIR}/${FILE}" "${TARGET_DIR}/${PRETTY_NAME}"


# --- create torrent and start seed
echo "[`date "+%Y-%m-%Oe %H:%M:%S"`]: building torrent" >> $LOG_FILE
buildtorrent -a http://mythtv.olin.edu:6969/announce -l 2097152 -q "${TARGET_DIR}/${PRETTY_NAME}" "${TMP_DIR}/${PRETTY_NAME}.torrent"
/usr/local/bin/rtorrent_fast_resume.pl ${TARGET_DIR} < "${TMP_DIR}/${PRETTY_NAME}.torrent" > "${TORRENT_DIR}/${PRETTY_NAME}.torrent"
rm "${TMP_DIR}/${PRETTY_NAME}.torrent"

# --- start transcode
# link into shared directory tree so transcode slaves can get to it
ln -s "${DIR}/${FILE}" "${SHARED_DIR}/${PRETTY_NAME}"
echo "[`date "+%Y-%m-%Oe %H:%M:%S"`]: kickoff transcode" >> $LOG_FILE
ssh -T tv.olin.edu <<EOI
/mnt/tv/scripts/transcode "${PRETTY_NAME}" < /dev/null > /mnt/tv/log/ssh.log 2>&1 &
EOI
echo "[`date "+%Y-%m-%Oe %H:%M:%S"`]: kickoff done" >> $LOG_FILE

