#!/bin/bash
# transcode
# transcodes the specified file
# called by the python daemon
#
# parameter: FILENAME
###

FILE=$*
NEWFILE=${FILE%.mpg}.mp4
LOG_FILE=/mnt/tv/log/transcode.log
SHARED_DIR=/var/lib/mythtv/recordings_pretty
TRANSCODE_DIR=/mnt/tv/transcoded
WEB_TORRENT_DIR=/mnt/tv/torrents
RTORRENT_DIR=/mnt/tv/rtorrent
TMP_DIR=/mnt/tv/tmp

# --- transcode
echo "[`date "+%Y-%m-%Oe %H:%M:%S"`]: transcoding ${FILE} " >> $LOG_FILE

HandBrakeCLI -i "${SHARED_DIR}/${FILE}" -o "${TRANSCODE_DIR}/${NEWFILE}" -e x264 -q 20.0 -a 1 -E faac -B 160 -6 dpl2 -R 48 -D 0.0 -f mp4 -m -x ref=2:bframes=2:subme=6:mixed-refs=0:weightb=0:8x8dct=0:trellis=0 -Y 720  > /dev/null

# --- build torrent and seed
echo "[`date "+%Y-%m-%Oe %H:%M:%S"`]: building torrent " >> $LOG_FILE

buildtorrent -a http://tv.olin.edu:6969/announce -l 2097152 -q "${TRANSCODE_DIR}/${NEWFILE}" "${WEB_TORRENT_DIR}/${NEWFILE}.torrent"
/usr/local/bin/rtorrent_fast_resume.pl ${TRANSCODE_DIR} < "${WEB_TORRENT_DIR}/${NEWFILE}.torrent" > "${RTORRENT_DIR}/${NEWFILE}.torrent"

# --- finished
rm "${SHARED_DIR}/${FILE}"
echo "[`date "+%Y-%m-%Oe %H:%M:%S"`]: finished " >> $LOG_FILE

